/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/

// Solution
// findTheDifference nomli function yaratdik u s va t parameterlarini qabul qiladi. Argument sifatida s ga random string beriladi va t ga ham random string faqat s dagi stringlar ozgartirilib beriladi va qoshimchasiga bitta s da mavjud bolmagan stringni return qilish kerak boladi. Avval men s va t stringlarni sortlab oldim. Va keyin for loop orqali t ni aylandim va shartida agar i s.length ga teng bo'lsa yoki s dagi i inchi element teng bolmasa t dagi i inchi elementga bizga t ning i inchi elementini qaytar shartini berdik. Shu tariqa qoshilgan 1 ta stringni topish mumkin. Agar argumentlarimiz bosh string boladigan bolsa bosh string return qilib beradi.
const findTheDifference = function (s, t) {
  s = s.split("").sort();
  t = t.split("").sort();

  for (let i = 0; i < t.length; i++) {
    if (i === s.length || s[i] !== t[i]) {
      return t[i];
    }
  }

  return "";
};
